'\" t
.\"     Title: desktoggle
.\"    Author: Raphael Scholer &lt;rascholer@gmail.com&gt;
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 09/16/2018
.\"    Manual: User Commands
.\"    Source: desktoggle
.\"  Language: English
.\"
.TH "DESKTOGGLE" "1" "09/16/2018" "desktoggle" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
desktoggle \- Hide all windows and show the desktop\&.
.SH "SYNOPSIS"
.sp
\fBdesktoggle\fR [\fIOPTION\&...\fR]
.SH "DESCRIPTION"
.sp
Hide all windows and show the desktop\&. When the command is run a second time all windows will be restored\&.
.SH "OPTIONS"
.PP
\fB\-\-help\fR
.RS 4
Show usage information\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Show version information\&.
.RE
.SH "AUTHOR"
.PP
\fBRaphael Scholer &lt;rascholer@gmail\&.com&gt;\fR
.RS 4
Author.
.RE
